all:
  hosts:
    node1:
      ip: 192.168.0.31
      ansible_host: 8.208.79.128
    node2:
      ip: 192.168.0.34
      ansible_host: 8.208.16.227
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
